##################################################
# File: camera.yaml                              #
##################################################

cameras:
  measurement_camera:
  - 0
  - acA1300-30um
  nozzle_camera:
  - 1
  - acA640-750um
max_camera: 2
params:
  px_mm: 1.52
  height: 960
  width: 640
